spring.application.name=gmtUser
spring.data.mongodb.uri=mongodb+srv://inventory-admin:inventory123@inventory.rbcanbq.mongodb.net/test?authSource=admin&replicaSet=atlas-13oxx1-shard-0&readPreference=primary&ssl=true
spring.data.mongodb.database=gmt
google.geocoding.api.key=AIzaSyBMYrXsp3G6qcV9bVibmp1h7wfLVDYkwDY
# server port - 5000 is used in AWS
server.port=5000